/**
 * Things that can happen. Useful for [debug] logging and displays.
 */
#pragma once
#include "util/types.h"
#include "arena.h"
#include "protocol.h"
#include <SFML/Network.hpp>

/**
 * ArenaEvent represents a thing that can happen in an game server. Used by
 * both ClientEvent and ServerEvent.
 *
 * This can be generated by the Arena.
 */

struct ArenaEvent {
  enum class Type {
    Chat, Broadcast, Join, Quit, NickChange, TeamChange, ModeChange
  } type;

 private:
  ArenaEvent(const Type type);

 public:
  ArenaEvent() = delete;

  optional<std::string> name, message, newName;
  optional<sky::Team> oldTeam, newTeam;
  optional<sky::ArenaMode> mode;

  std::string print() const;

  static ArenaEvent Chat(const std::string &name, const std::string &message);
  static ArenaEvent Broadcast(const std::string &message);
  static ArenaEvent Join(const std::string &name);
  static ArenaEvent Quit(const std::string &name);
  static ArenaEvent NickChange(const std::string &name,
                               const std::string &newName);
  static ArenaEvent TeamChange(const std::string &name, const sky::Team oldTeam,
                               const sky::Team newTeam);
  static ArenaEvent ModeChange(const sky::ArenaMode mode);
};

/**
 * A thing that can happen on a server. Subordinates ArenaEvent.
 */

struct ServerEvent {
  enum class Type {
    Start, Event, Stop, Connect, Disconnect
  } type;

 private:
  ServerEvent(const Type type);

 public:
  ServerEvent() = delete;

  optional<Port> port;
  optional<std::string> name;
  optional<ArenaEvent> arenaEvent;
  optional<double> uptime;

  std::string print() const;

  static ServerEvent Start(const Port port,
                           const std::string &name);
  static ServerEvent Event(const ArenaEvent &arenaEvent);
  static ServerEvent Stop(const double uptime);
  static ServerEvent Connect(const std::string &name);
  static ServerEvent Disconnect(const std::string &name);
};

/**
 * A thing that can happen on a client. Subordinates ArenaEvent.
 */

enum class DisconnectType {
  Graceful, Timeout
};

struct ClientEvent {
  enum class Type {
    Connect, Event, Disconnect
  } type;

 private:
  ClientEvent(const Type type);

 public:
  ClientEvent() = delete;

  optional<std::string> name;
  optional<sf::IpAddress> ipAddr;
  optional<ArenaEvent> arenaEvent;
  optional<double> uptime;
  optional<DisconnectType> disconnect;

  std::string print() const;

  static ClientEvent Connect(const std::string &name,
                             const sf::IpAddress &ipAddr);
  static ClientEvent Event(const ArenaEvent &arenaEvent);
  static ClientEvent Disconnect(const double uptime,
                                const DisconnectType disconnect);
};
